[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", default-features = false, features = [
    "macros",
    "rt",
    "net",
    "io-util",
] }
